name: MiniBoosters
version: ${project.version}
main: me.reed.miniboosters.MiniBoosters
api-version: 1.16
authors: [ Reed22 ]
description: ${project.description}
commands:
  booster:
    description: The plugin's core command used to activate, deactivate, and check status on server boosters.
    usage: /<command>