name: MiniBoosters
version: ${project.version}
main: me.reed.miniboosters.MiniBoosters
api-version: 1.16
authors: [ Reed22 ]
description: This is a plugin that allows you to boost certain things in your world, such as the value of exp!
commands:
  booster:
    description: Activates or deactivates double exp!
    usage: /<command>
  exptracker:
    description: Activates or deactivates the exp pickup tracker!
    usage: /<command>