name: MiniBoosters
version: ${project.version}
main: me.reed.reedsplugin.MiniBoosters
api-version: 1.16
authors: [ Reed22 ]
description: A collection of the results of Reed screwing around with code, 90% of the time unsuccessfully.
commands:
  doubleexp:
    description: Activates or deactivates double exp!
    usage: /<command>
  exptracker:
    description: Activates or deactivates the exp pickup tracker!
    usage: /<command>